version: '3.7'
services:
  proxy:
    image: nginx
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 0
        delay: 5s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_network"
        - "traefik.http.routers.registery.entrypoints=web"
        - "traefik.http.routers.registery.service=registery"
        - "traefik.http.routers.registery.rule=Host(`registery.exlinetr.com`)"
        - "traefik.http.services.registery.loadbalancer.server.port=80"
        - "traefik.http.services.registery.loadbalancer.server.scheme=http"
        # - "traefik.http.routers.registery-docker.entrypoints=web"
        # - "traefik.http.routers.registery-docker.service=registery-docker"
        # - "traefik.http.routers.registery-docker.rule=Host(`registery.exlinetr.com`) && HeadersRegexp(`User-Agent`, `.*Docker.*`)"
        # - "traefik.http.routers.registery-docker.middlewares=https-to-http-proxy"
        # - "traefik.http.services.registery-docker.loadbalancer.server.port=5000"
        # - "traefik.http.services.registery-docker.loadbalancer.server.scheme=http"
        # - "traefik.http.routers.registery.middlewares=https-to-http-proxy"
        # - "traefik.http.middlewares.https-to-http-proxy.headers.customrequestheaders.X-Forwarded-Proto=https"
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    networks:
      - registry-net
      - traefik_network

  hub:
    image: sonatype/nexus3:3.22.1
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 0
        delay: 5s
    volumes:
      - type: bind
        source: /mnt/storage/exlinetr/nexus
        target: /nexus-data
    networks:
      - registry-net
      - traefik_network

configs:
  nginx_config:
    name: "exlinetr_registery_proxy_nginx.config"
    file: nginx.conf

networks:
  registry-net:
  traefik_network:
    external: true