version: '3.7'
services:
  ui:
    image: sonatype/nexus3:3.22.1
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 0
        delay: 5s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_network"
        - "traefik.http.routers.registery.service=registery"
        - "traefik.http.routers.registery.rule=Host(`registery.exlinetr.com`)"
        - "traefik.http.routers.registery.entrypoints=web"
        - "traefik.http.middlewares.https-to-http-proxy.headers.customrequestheaders.X-Forwarded-Proto=https"
        - "traefik.http.routers.registery.middlewares=https-to-http-proxy"
        - "traefik.http.services.registery.loadbalancer.server.port=8081"
        - "traefik.http.services.registery.loadbalancer.server.scheme=http"
    volumes:
      - type: bind
        source: /mnt/storage/exlinetr/nexus
        target: /nexus-data
    networks:
      - registry-ui-net
      - traefik_network

networks:
  registry-ui-net:
  traefik_network:
    external: true